/**
 * Calls the Gemini API to get a contextual response for a fan's question.
 * Uses the current fan context and the system's latest recommendation as grounding.
 * Includes a simple retry mechanism for rate limiting (HTTP 429).
 * 
 * @param {string} userQuestion - The question asked by the fan.
 * @param {Object} currentContext - The fan's current context state.
 * @param {Object} lastRecommendation - The latest routing recommendation generated by the decision engine.
 * @returns {Promise<string>} The textual response from the assistant.
 */
export async function askAssistant(userQuestion, currentContext, lastRecommendation) {
  const delay = (ms) => new Promise(res => setTimeout(res, ms));
  const maxAttempts = 2; // initial try + 1 retry

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      const response = await fetch('/api/gemini', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          question: userQuestion,
          context: currentContext,
          lastRecommendation: lastRecommendation
        })
      });

      if (!response.ok) {
        if (response.status === 429) {
          // If we hit a rate limit, apply backoff and retry if attempts remain
          if (attempt < maxAttempts) {
            await delay(1500); // Wait 1.5 seconds before retry
            continue;
          }
          // After all attempts exhaust, return specific rate limit message
          return "Assistant is a bit busy right now, please wait a few seconds and try again.";
        }
        if (response.status === 500) {
          return "Error: Server configuration error or API connection issue. Please check your server environment variables.";
        }
        throw new Error(`API returned status: ${response.status}`);
      }

      const data = await response.json();
      
      // Extract the text safely
      if (data.candidates && data.candidates.length > 0 && data.candidates[0].content && data.candidates[0].content.parts.length > 0) {
        return data.candidates[0].content.parts[0].text;
      }
      
      return "I'm sorry, I couldn't process an answer at this time.";

    } catch (error) {
      console.error("Error calling backend proxy:", error);
      // For general network/parsing errors not caught by the 429 block
      return "I'm having trouble connecting to my brain right now. Please try again later or follow the on-screen recommendations.";
    }
  }
}
